/*
--------------------------------------------------------------------------------

  Photon Shader by SixthSurge

  program/c3_taau_prep:
  Calculate neighborhood limits for TAAU

--------------------------------------------------------------------------------
*/

#include "/include/global.glsl"

#ifdef INDIRECT_LIGHTING
layout(location = 0) out vec4 indirect_bounce2;
#else
layout(location = 0) out vec3 min_color;
layout(location = 1) out vec3 max_color;
#endif

#ifdef INDIRECT_LIGHTING
/* RENDERTARGETS: 1 */
#else
/* RENDERTARGETS: 1,2 */
#endif

in vec2 uv;

uniform sampler2D colortex0;
uniform sampler2D depthtex0;
uniform mat4 gbufferProjection;
uniform mat4 gbufferProjectionInverse;
uniform float near, far;
uniform vec2 view_res;
uniform vec2 view_pixel_size;
uniform vec2 taa_offset;
uniform int frameCounter;
#ifdef INDIRECT_LIGHTING
uniform sampler2D colortex2; // first-bounce irradiance generated by c2
uniform sampler2D colortex3; // receiver albedo written by c2
uniform sampler2D colortex17; // full-resolution 2x2 depth-slice irradiance cache
#endif

#include "/include/utility/color.glsl"
#include "/include/utility/space_conversion.glsl"
#ifdef INDIRECT_LIGHTING
#include "/include/lighting/indirect_lighting.glsl"
#endif

vec3 min_of(vec3 a, vec3 b, vec3 c, vec3 d, vec3 f) {
    return min(a, min(b, min(c, min(d, f))));
}

vec3 max_of(vec3 a, vec3 b, vec3 c, vec3 d, vec3 f) {
    return max(a, max(b, max(c, max(d, f))));
}

// Invertible tonemapping operator (Reinhard) applied before blending the
// current and previous frames Improves the appearance of emissive objects
vec3 reinhard(vec3 rgb) { return rgb / (rgb + 1.0); }

void main() {
    ivec2 texel = ivec2(gl_FragCoord.xy);

#ifdef INDIRECT_LIGHTING
    indirect_bounce2 = vec4(0.0);
    float depth = texelFetch(depthtex0, texel, 0).x;
    if (depth < 0.99999 && depth >= hand_depth) {
        vec3 receiver_view_pos = indirect_reconstruct_view_position(uv, depth);
        vec3 receiver_normal = indirect_reconstruct_normal(uv);
        vec3 receiver_albedo = max(texelFetch(colortex3, texel, 0).rgb, vec3(0.02));

        float gather_weight = 0.0;
        vec3 bounce2 = indirect_gather_bounce2(
            uv, receiver_view_pos, receiver_normal, receiver_albedo, gather_weight
        );

        float receiver_depth = abs(screen_to_view_space_depth(gbufferProjectionInverse, depth));
        vec3 cache_bounce = indirect_sample_cache(uv, receiver_depth);
        bounce2 += cache_bounce * indirect_cache_strength * 0.06 * receiver_albedo;
        bounce2 *= INDIRECT_SECOND_BOUNCE_ENERGY * clamp01(gather_weight + 0.25);

        indirect_bounce2 = vec4(max(bounce2, vec3(0.0)), 1.0);
    }

#else
    // Fetch 3x3 neighborhood
    // a b c
    // d e f
    // g h i
    vec3 a = texelFetch(colortex0, texel + ivec2(-1, 1), 0).rgb;
    vec3 b = texelFetch(colortex0, texel + ivec2(0, 1), 0).rgb;
    vec3 c = texelFetch(colortex0, texel + ivec2(1, 1), 0).rgb;
    vec3 d = texelFetch(colortex0, texel + ivec2(-1, 0), 0).rgb;
    vec3 e = texelFetch(colortex0, texel, 0).rgb;
    vec3 f = texelFetch(colortex0, texel + ivec2(1, 0), 0).rgb;
    vec3 g = texelFetch(colortex0, texel + ivec2(-1, -1), 0).rgb;
    vec3 h = texelFetch(colortex0, texel + ivec2(0, -1), 0).rgb;
    vec3 i = texelFetch(colortex0, texel + ivec2(1, -1), 0).rgb;

    // Convert to YCoCg
    a = rgb_to_ycocg(reinhard(a));
    b = rgb_to_ycocg(reinhard(b));
    c = rgb_to_ycocg(reinhard(c));
    d = rgb_to_ycocg(reinhard(d));
    e = rgb_to_ycocg(reinhard(e));
    f = rgb_to_ycocg(reinhard(f));
    g = rgb_to_ycocg(reinhard(g));
    h = rgb_to_ycocg(reinhard(h));
    i = rgb_to_ycocg(reinhard(i));

    // Soft minimum and maximum ("Hybrid Reconstruction Antialiasing")
    //        b         a b c
    // (min d e f + min d e f) / 2
    //        h         g h i
    min_color = min_of(b, d, e, f, h);
    min_color += min_of(min_color, a, c, g, i);
    min_color *= 0.5;

    max_color = max_of(b, d, e, f, h);
    max_color += max_of(max_color, a, c, g, i);
    max_color *= 0.5;

    min_color = min_color * 0.5 + 0.5;
    max_color = max_color * 0.5 + 0.5;
#endif
}
//----------------------------------------------------------------------------//
